suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(tidyr);library(readr);library(patchwork)})
p <- sub('^--file=', '', commandArgs(FALSE)[grep('^--file=',commandArgs(FALSE))][1])
root <- normalizePath(file.path(dirname(p),'..'),winslash='/')
d <- read_csv(file.path(root,'source_data','figureS3_run_metrics.csv'),show_col_types=FALSE)
lev <- c('Full model','No source indicator','No pretraining')
d$variant <- factor(d$variant,levels=rev(lev))
pal <- c('Full model'='#0B4C78','No source indicator'='#6D9391','No pretraining'='#A6ADB5')
theme_set(theme_classic(base_size=8,base_family='Arial')+theme(axis.text=element_text(colour='#263542'),axis.line=element_line(linewidth=.3),legend.position='none',plot.margin=margin(6,8,6,8),plot.tag=element_text(face='bold',size=11)))
s <- d %>% group_by(variant) %>% summarise(value=100*mean(hmean),sd=100*sd(hmean),.groups='drop')
a <- ggplot(d,aes(100*hmean,variant,colour=variant))+geom_point(size=1.6,alpha=.6)+geom_errorbar(data=s,aes(x=value,xmin=value-sd,xmax=value+sd),orientation='y',width=.15,linewidth=.6)+geom_point(data=s,aes(x=value),shape=18,size=3)+scale_colour_manual(values=pal)+labs(x='Harmonic mean Top-10 (%)',y=NULL)+scale_x_continuous(expand=expansion(mult=c(.1,.15)))
long <- d %>% pivot_longer(c(compound_to_profile,profile_to_compound,gene_to_profile,profile_to_gene),names_to='direction',values_to='value')
long$direction <- factor(long$direction,levels=c('compound_to_profile','profile_to_compound','gene_to_profile','profile_to_gene'),labels=c('C -> P','P -> C','G -> P','P -> G'))
h <- long %>% group_by(variant,direction) %>% summarise(value=100*mean(value),.groups='drop')
b <- ggplot(h,aes(direction,variant,fill=value))+geom_tile(colour='white',linewidth=1)+geom_text(aes(label=sprintf('%.1f',value)),size=2.7)+scale_fill_gradient(low='#EFF4F6',high='#78AABD')+labs(x='Retrieval direction',y=NULL)+theme(axis.line=element_blank(),axis.ticks=element_blank())
full <- d %>% filter(variant=='Full model') %>% select(seed,full=hmean)
delta <- d %>% filter(variant!='Full model') %>% left_join(full,by='seed') %>% mutate(delta=100*(hmean-full))
c <- ggplot(delta,aes(factor(seed),delta,colour=variant,group=variant))+geom_hline(yintercept=0,linetype=2,linewidth=.35,colour='#A6ADB5')+geom_line(linewidth=.6)+geom_point(size=2)+scale_colour_manual(values=pal)+labs(x='Training seed',y='Change in HMean Top-10 (pp)',colour=NULL)+theme(legend.position='bottom',legend.text=element_text(size=7))
fig <- (a|b)/c+plot_layout(heights=c(1,1))+plot_annotation(tag_levels='a')
base <- file.path(root,'figures','figureS3');dir.create(dirname(base),recursive=TRUE,showWarnings=FALSE)
for(ext in c('png','tiff','pdf','svg')){
 dev <- switch(ext,png=ragg::agg_png,tiff=ragg::agg_tiff,pdf=cairo_pdf,svg=svglite::svglite)
 ggsave(paste0(base,'.',ext),fig,width=183,height=132,units='mm',dpi=600,device=dev,bg='white')
}
writeLines(capture.output(sessionInfo()),file.path(root,'figures','sessionInfo_S3.txt'))
